/**
 * @file app_config.h
 * @author OpenFeeder Team <https://github.com/orgs/OpenFeeder/people>
 * @version 1.0
 * @date
 */

#ifndef _APP_CONFIG_HEADER_H
#define _APP_CONFIG_HEADER_H

#include "min_ini.h"

#define sizearray(a)  (sizeof(a) / sizeof((a)[0]))

#define DEFAULT_LOG_SEPARATOR ","

#define DEFAULT_GUILLOTINE_TIME_OFFSET 5000

typedef enum
{
    INI_READ_OK = 0,

    INI_PB_SCENARIO_NUM, 

    INI_PB_SITEID_ZONE,

    INI_PB_TIME_WAKEUP_HOUR,
    INI_PB_TIME_WAKEUP_MINUTE,

    INI_PB_TIME_SLEEP_HOUR, 
    INI_PB_TIME_SLEEP_MINUTE, 

    INI_PB_ATTRACTIVE_LEDS_RED_A,
    INI_PB_ATTRACTIVE_LEDS_GREEN_A, 
    INI_PB_ATTRACTIVE_LEDS_BLUE_A,

    INI_PB_ATTRACTIVE_LEDS_RED_B, 
    INI_PB_ATTRACTIVE_LEDS_GREEN_B, 
    INI_PB_ATTRACTIVE_LEDS_BLUE_B,

    INI_PB_ATTRACTIVE_LEDS_ALT_DELAY, 

    INI_PB_ATTRACTIVE_LEDS_ON_HOUR, 
    INI_PB_ATTRACTIVE_LEDS_ON_MINUTE, 

    INI_PB_ATTRACTIVE_LEDS_OFF_HOUR, 
    INI_PB_ATTRACTIVE_LEDS_OFF_MINUTE, 

    INI_PB_ATTRACTIVE_LEDS_PATTERN, 
        
    INI_PB_ATTRACTIVE_LEDS_PATTERN_PERCENT,
            
    INI_PB_DOOR_CLOSE_POSITION, 
    INI_PB_DOOR_OPEN_POSITION,
    INI_PB_DOOR_CLOSING_SPEED, 
    INI_PB_DOOR_OPENING_SPEED, 

    INI_PB_DOOR_OPEN_DELAY, 
    INI_PB_DOOR_CLOSE_DELAY, 

    INI_PB_DOOR_REMAIN_OPEN,

    INI_PB_DOOR_REWARD_PROBABILITY,

    INI_PB_DOOR_OPEN_HOUR,
    INI_PB_DOOR_OPEN_MINUTE, 

    INI_PB_DOOR_CLOSE_HOUR, 
    INI_PB_DOOR_CLOSE_MINUTE, 
        
    INI_PB_DOOR_MAX_OFFSET,

    INI_PB_REWARD_ENABLE,
    INI_PB_REWARD_TIMEOUT,  
    INI_PB_REWARD_PROBABILITY,
           
    INI_PB_TIMEOUTS_SLEEP,
    INI_PB_TIMEOUTS_PIR, 
    INI_PB_TIMEOUTS_UNIQUE_VISIT,
        
    INI_PB_PIT_TAG_DENIED, 
    INI_PB_PIT_TAG_ACCEPTED,

    INI_PB_PIT_TAG_COLOR_A,
    INI_PB_PIT_TAG_COLOR_B,
        
    INI_PB_PIT_TAG_LEFT,
    INI_PB_PIT_TAG_RIGHT,
    INI_PB_PIT_TAG_TOP,
    INI_PB_PIT_TAG_BOTTOM,
            
    INI_PB_PIT_TAG_LED_1,
    INI_PB_PIT_TAG_LED_2,
    INI_PB_PIT_TAG_LED_3,
    INI_PB_PIT_TAG_LED_4,
            
    INI_PB_PUNISHMENT_DELAY, 
    INI_PB_PUNISHMENT_PROBA_THRESH,
        
    INI_PB_DOOR_HABITUATION, 
       
    INI_PB_LOGS_BIRDS,
    INI_PB_LOGS_UDID,
    INI_PB_LOGS_EVENTS,
    INI_PB_LOGS_ERRORS,
    INI_PB_LOGS_BATTERY,
    INI_PB_LOGS_RFID,
        
    INI_PB_CHECK_FOOD_LEVEL,
        
    INI_PB_SECURITY_BIRD_REWARD_REOPEN,
    INI_PB_SECURITY_GUILLOTINE,
    INI_PB_SECURITY_GUILLOTINE_OFFSET,
        
    INI_PB_STIMULI_ALT_DELAY,
    INI_PB_STIMULI_NUM
            
} INI_READ_STATE;

bool config_set( void );
FILEIO_RESULT config_find_ini( void );
INI_READ_STATE config_read_ini( void );
void config_print( void );
void getIniPbChar( INI_READ_STATE, char *, uint8_t );
FILEIO_RESULT read_PIT_tags( void );
FILEIO_RESULT read_reward_probabilities( void );

#endif /* _APP_CONFIG_HEADER_H */


/*******************************************************************************
 End of File
 */
