/* This file is automatically generated during build process
 * under MPLAB X and should not be manually edited */

#ifndef _APP_VERSION_H
#define _APP_VERSION_H

#define FW_NAME "fw02_1"
#define FW_VERSION_MAJOR 1
#define FW_VERSION_MINOR 2
#define FW_VERSION_PATCH 0

#endif /* _APP_VERSION_H */
