/* This file is automatically generated during build process
 * under MPLAB X and should not be manually edited */

#ifndef _APP_STIMULI_H
#define _APP_STIMULI_H

typedef struct
{
    uint8_t alt_delay;
    uint8_t alt_sec_elapsed;
    uint8_t max_stimuli;
    uint8_t current_stimuli;
    bool enable;    
} APP_DATA_STIMULI;

#endif /* _APP_STIMULI_H */
